package sample.data.jpa.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import sample.data.jpa.domain.*;
import sample.data.jpa.service.MetricsRepository;
import sample.data.jpa.service.UserRepository;
import java.util.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private MetricsRepository metricsRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String fullName
			, @RequestParam String emailId, @RequestParam String password, @RequestParam String deviceId) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		User n = new User();
		n.setName(fullName);
		n.setPassword(password);
		n.setEmail(emailId);
		n.setDeviceid(deviceId);
		userRepository.save(n);
		return "Saved";
	}

    @RequestMapping(value ="/device/{deviceId}/Metric", method = RequestMethod.PUT)
    @ResponseBody
    public ResponseEntity <JSONtoVitalsObjectMapper> addVitalsInformation(@PathVariable("deviceId") String deviceId, @RequestBody JSONtoVitalsObjectMapper jvObject){
	        // Now I have JV object .
        // get userid from device ID
        //Metrics metrics = metricsRepository.findAllByDeviceIdOrderByEntryTimeStamp(deviceId);
        // Construct method for metrics repository
        Metrics metricsTemp = new Metrics();
        metricsTemp.setEntryTimeStamp(jvObject.getEntryTimeStamp());
        metricsTemp.setMetricType("Temperature");
        metricsTemp.setMetricValue(jvObject.getTemperature());
        metricsTemp.setDeviceid(deviceId);
        metricsRepository.save(metricsTemp);

        Metrics metricsPulse = new Metrics();
        metricsPulse.setEntryTimeStamp(jvObject.getEntryTimeStamp());
        metricsPulse.setMetricType("PulseRate");
        metricsPulse.setMetricValue(jvObject.getPulseRate());
        metricsPulse.setDeviceid(deviceId);
        metricsRepository.save(metricsPulse);

        Metrics metricsSPO2 = new Metrics();
        metricsSPO2.setEntryTimeStamp(jvObject.getEntryTimeStamp());
        metricsSPO2.setMetricType("SPO2");
        metricsSPO2.setMetricValue(jvObject.getSpo2());
        metricsSPO2.setDeviceid(deviceId);
        metricsRepository.save(metricsSPO2);

        return new ResponseEntity(HttpStatus.OK);
    }
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/metrics")
	public @ResponseBody Iterable<Metrics> getAllMetrics(){

		return metricsRepository.findAll();
	}

    @GetMapping(path="/metrics/deviceId")
    public @ResponseBody Iterable<MetricsWrapper> getUserHistoricalData(@RequestParam String deviceId){
	    Iterable <Metrics> metrics = metricsRepository.findTop3ByDeviceidOrderByEntryTimeStampDesc(deviceId);
	    List <MetricsWrapper> MetricsWrapperList = new ArrayList<>();

	    for (Metrics metric : metrics){
	        Iterable <Metrics> historicalData = metricsRepository.findTop50ByMetricTypeOrderByEntryTimeStampDesc(metric.getMetricType());
	        MetricsWrapper merticsWrapperObject = new MetricsWrapper(metric,historicalData);
            MetricsWrapperList.add(merticsWrapperObject);
        }
        return MetricsWrapperList;
    }
}
